[package]
name = "s3s-codegen"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
heck = "0.4.1"
regex = "1.7.3"
serde = { version = "1.0.159", features = ["derive"] }
serde_json = { version = "1.0.95", features = ["preserve_order"] }
serde_urlencoded = "0.7.1"
