logLevel = "critical"

[server]
type = "s3"
host = "127.0.0.1"
port = 4356
validateCredentials = false

[[middlewares]]
type = "cache"
cacheSize = 500_000_000
ttl = 1000_000
tti = 1000_000

[middlewares.ops.GetObject]
enabled = true

[middlewares.ops.HeadObject]
enabled = true

[middlewares.ops.ListObjects]
enabled = true

[middlewares.ops.ListObjectVersions]
enabled = true

[middlewares.ops.HeadBucket]
enabled = true

[middlewares.ops.ListBuckets]
enabled = true

[[middlewares]]
type = "identity"

[client]
type = "s3"
endpointUrl = "http://localhost:9000"
forcePathStyle = true
enableHttp2 = true
insecure = true
connectTimeout = 10_000
# readTimeout = 10_000
# operationTimeout = 10_000
# operationAttemptTimeout = 10_000
maxRetryAttempts = 3

[client.credentials]
accessKeyId = "user"
secretKey = "password"
