version: '2'

services:
  minio:
    image: 'bitnami/minio:latest'
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=user
      - MINIO_ROOT_PASSWORD=password
      - MINIO_NOTIFY_WEBHOOK_ENABLE_S3P=on
      - MINIO_NOTIFY_WEBHOOK_ENDPOINT_S3P=localhost:4357